### ISSUE TITLE
Change key bindings from mod+1 to alt+mod+1

### ISSUE THREAD

**Issue by huyz** [vipzhicheng/logseq-plugin-heading-level-shortcuts#2]
The bindings conflict with https://github.com/pengx17/logseq-plugin-tabs , which correctly uses mod+1 for selecting tabs just as in Chrome web browser.

alt+mod+1 is more commonly used for setting the heading level. See https://support.google.com/docs/answer/179738?hl=en&co=GENIE.Platform%3DDesktop#zippy=%2Cmac-shortcuts and search for "Apply heading style" to see.

**Comment by tiankonganddahai** [comment]
Agree this too,perhaps how can i change the shortcuts to mod+opt+1/2/3... myself by edit config file?

**Comment by vipzhicheng** [comment]
I added a settings file now, please upgrade and test.

**Comment by huyz** [comment]
Works. Thanks!
